# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year-:month-:day-:title/

# Setup
title:               KOONN
tagline:             'pounding the rock'
description:         'I am a beginner in data science.'
                     # 'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              koonn
  url:               https://twitter.com/itoama
  email:             konnie211@gmail.com

# Custom vars
version:             1.0.0
markdown: kramdown

#gems
gems: [jekyll-paginate]
